/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */
export interface Config {
    collections: {
        announcements: Announcement;
        'case-studies': CaseStudy;
        'community-help': CommunityHelp;
        docs: Doc;
        media: Media;
        pages: Page;
        posts: Post;
